-- This file is autogenerated from regen-schema.ts
alter table private_user_messages
add constraint private_user_messages_channel_id_fkey foreign key (channel_id) references private_user_message_channels (id) on update cascade on delete cascade;

alter table private_user_seen_message_channels
add constraint channel_id_fkey foreign key (channel_id) references private_user_message_channels (id) on update cascade on delete cascade;

alter table private_user_message_channel_members
add constraint channel_id_fkey foreign key (channel_id) references private_user_message_channels (id) on update cascade on delete cascade;
