-- This file is autogenerated from regen-schema.ts
create table if not exists
  love_questions (
    answer_type text default 'free_response'::text not null,
    created_time timestamp with time zone default now() not null,
    creator_id text not null,
    id bigint generated always as identity primary key, -- love_questions_pkey
    importance_score numeric default 0 not null,
    multiple_choice_options jsonb,
    question text not null
  );

-- Row Level Security
alter table love_questions enable row level security;

-- Policies
drop policy if exists "public read" on love_questions;

create policy "public read" on love_questions for all using (true);

-- Indexes
/*
DROP INDEX IF EXISTS love_questions_pkey;

CREATE UNIQUE INDEX love_questions_pkey ON public.love_questions USING btree (id);

*/
