-- This file is autogenerated from regen-schema.ts
create table if not exists
  love_waitlist (
    created_time timestamp with time zone default now() not null,
    email text not null,
    id bigint generated always as identity primary key -- love_waitlist_pkey
  );

-- Row Level Security
alter table love_waitlist enable row level security;

-- Policies
drop policy if exists "anon insert" on love_waitlist;

create policy "anon insert" on love_waitlist for insert
with
  check (true);

-- Indexes
/*
DROP INDEX IF EXISTS love_waitlist_pkey;

CREATE UNIQUE INDEX love_waitlist_pkey ON public.love_waitlist USING btree (id);

*/
