-- This file is autogenerated from regen-schema.ts
create table if not exists
  love_ships (
    created_time timestamp with time zone default now() not null,
    creator_id text not null,
    ship_id text default random_alphanumeric (12) not null,
    target1_id text not null,
    target2_id text not null,
    constraint love_ships_pkey primary key (creator_id, ship_id)
  );

-- Row Level Security
alter table love_ships enable row level security;

-- Policies
drop policy if exists "public read" on love_ships;

create policy "public read" on love_ships for
select
  using (true);

-- Indexes
/*
DROP INDEX IF EXISTS love_ships_pkey;

CREATE UNIQUE INDEX love_ships_pkey ON public.love_ships USING btree (creator_id, ship_id);

*/
drop index if exists love_ships_target1_id;

create index love_ships_target1_id on public.love_ships using btree (target1_id);

drop index if exists love_ships_target2_id;

create index love_ships_target2_id on public.love_ships using btree (target2_id);
