-- This file is autogenerated from regen-schema.ts
create table if not exists
  love_stars (
    created_time timestamp with time zone default now() not null,
    creator_id text not null,
    star_id text default random_alphanumeric (12) not null,
    target_id text not null,
    constraint love_stars_pkey primary key (creator_id, star_id)
  );

-- Row Level Security
alter table love_stars enable row level security;

-- Policies
drop policy if exists "public read" on love_stars;

create policy "public read" on love_stars for
select
  using (true);

-- Indexes
/*
DROP INDEX IF EXISTS love_stars_pkey;

CREATE UNIQUE INDEX love_stars_pkey ON public.love_stars USING btree (creator_id, star_id);

*/
