-- This file is autogenerated from regen-schema.ts
create table if not exists
  private_user_messages (
    channel_id bigint not null,
    content jsonb not null,
    created_time timestamp with time zone default now() not null,
    id bigint primary key private_user_messages_pkey generated always as identity not null,
    old_id bigint,
    user_id text not null,
    visibility text default 'private'::text not null
  );

-- Foreign Keys (in foreign_keys.sql)
-- ALTER TABLE private_user_messages
-- ADD CONSTRAINT private_user_messages_channel_id_fkey FOREIGN KEY (channel_id) REFERENCES private_user_message_channels(id) ON UPDATE CASCADE ON DELETE CASCADE;
--
-- Row Level Security
alter table private_user_messages enable row level security;

-- Indexes
drop index if exists private_user_messages_channel_id_idx;

create index private_user_messages_channel_id_idx on public.private_user_messages using btree (channel_id, created_time desc);

/*
DROP INDEX IF EXISTS private_user_messages_pkey;

CREATE UNIQUE INDEX private_user_messages_pkey ON public.private_user_messages USING btree (id);

*/
