-- This file is autogenerated from regen-schema.ts
create table if not exists
  private_users (
    data jsonb not null,
    id text primary key private_users_pkey not null
  );

-- Row Level Security
alter table private_users enable row level security;

-- Policies
drop policy if exists "private read" on private_users;

create policy "private read" on private_users for
select
  using ((firebase_uid () = id));

-- Indexes
/*
DROP INDEX IF EXISTS private_users_pkey;

CREATE UNIQUE INDEX private_users_pkey ON public.private_users USING btree (id);

*/
