-- This file is autogenerated from regen-schema.ts
create table if not exists
  private_user_message_channel_members (
    channel_id bigint not null,
    created_time timestamp with time zone default now() not null,
    id bigint primary key private_user_message_channel_members_pkey generated always as identity not null,
    notify_after_time timestamp with time zone default now() not null,
    role text default 'member'::text not null,
    status text default 'proposed'::text not null,
    user_id text not null
  );

-- Foreign Keys (in foreign_keys.sql)
-- ALTER TABLE private_user_message_channel_members
-- ADD CONSTRAINT channel_id_fkey FOREIGN KEY (channel_id) REFERENCES private_user_message_channels(id) ON UPDATE CASCADE ON DELETE CASCADE;
--
-- Row Level Security
alter table private_user_message_channel_members enable row level security;

-- Indexes
/*
DROP INDEX IF EXISTS private_user_message_channel_members_pkey;

CREATE UNIQUE INDEX private_user_message_channel_members_pkey ON public.private_user_message_channel_members USING btree (id);

*/
drop index if exists pumcm_members_idx;

create index pumcm_members_idx on public.private_user_message_channel_members using btree (channel_id, user_id);

drop index if exists unique_user_channel;

create unique index unique_user_channel on public.private_user_message_channel_members using btree (channel_id, user_id);
