-- This file is autogenerated from regen-schema.ts
create table if not exists
  temp_users (
    created_time timestamp with time zone,
    id text,
    name text,
    private_user_data jsonb,
    user_data jsonb,
    username text
  );

-- Row Level Security
alter table temp_users enable row level security;
