name: CI checks for web workspace

on:
  push:
    branches: ['main']
    paths: ['web/**/*', '!**/*.{txt,md}']
  pull_request:
    branches: ['main']
    paths: ['web/**/*', '!**/*.{txt,md}']

defaults:
  run:
    working-directory: 'web'

jobs:
  Prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24.3.0'
          cache: npm
          cache-dependency-path: 'package.json'
      - name: Install yarn
        run: npm install -g yarn
      - name: Install dependencies
        run: yarn install --immutable
      - name: Run prettier
        run: yarn prettier . --check --ignore-unknown
  ESLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24.3.0'
          cache: npm
          cache-dependency-path: 'package.json'
      - name: Install yarn
        run: npm install -g yarn
      - name: Install dependencies
        run: yarn install --immutable
      - name: Run ESLint
        run: yarn eslint .
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24.3.0'
          cache: npm
          cache-dependency-path: 'package.json'
      - name: Install yarn
        run: npm install -g yarn
      - name: Install dependencies
        run: yarn install --immutable
      - name: Compile with tsc
        run: yarn tsc --noEmit --strict
